import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.scss";
import { cn } from "@/lib/utils";
import Navbar from "@/components/layout/navbar";
import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/layout/footer";
import ContextWrapper from "@/lib/contexts/context-wrapper";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ContextWrapper>
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable
          )}
        >
          <Navbar />
          {children}
          <Footer />
          <Toaster />
        </body>
      </ContextWrapper>
    </html>
  );
}
